# Generated by Django 3.1.2 on 2025-08-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('Patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=250)),
                ('lastname', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('mobile_number', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('blood_group', models.CharField(blank=True, choices=[('O+', 'Oplus'), ('A+', 'Aplus'), ('B+', 'Bplus'), ('O-', 'Ominus'), ('A-', 'Aminus'), ('B-', 'Bminus'), ('AB+', 'ABplus'), ('AB-', 'ABminus')], max_length=10)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('appointment_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.BooleanField(default=False)),
            ],
        ),
    ]
