# Generated by Django 3.1.2 on 2025-08-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('address', models.TextField()),
                ('specialization', models.CharField(max_length=100)),
                ('qualification', models.CharField(blank=True, max_length=200, null=True)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('license_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('hospital', models.CharField(blank=True, max_length=200, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('availability_days', models.CharField(blank=True, max_length=200, null=True)),
                ('availability_time', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='doctor_profiles/')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('reviews_count', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('profile_created_at', models.DateTimeField(auto_now_add=True)),
                ('profile_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
